name: Update packages

on:
  workflow_dispatch:
  schedule:
  # Every day at 4am
  - cron: "0 4 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: "Prepare environment"
        run: |
          sudo apt update
          sudo apt install git
    
      - name: "Checkout"
        uses: actions/checkout@v2
      
      - name: "Checkout AutoEQ"    
        uses: actions/checkout@v2
        with:
          repository: jaakkopasanen/AutoEq
          path: autoeq/
          
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      - name: Run packaging script
        run: |
          cd autoeq
          python ../package.py
          
      - name: Collect exported data
        run: |
          mv autoeq/archive.tar.gz .
          mv autoeq/export/index.json .
          mv autoeq/export/version.json .
          rm -rf autoeq
          
      - name: Publish changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update archive
          file_pattern: ./*.tar.gz ./*.json
